USE ROLE ACCOUNTADMIN;

-- Create the TRANSFORM role
CREATE ROLE IF NOT EXISTS TRANSFORM;

-- Create COMPUTE_WH warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;

-- Create MOVIELENS_DB database
CREATE DATABASE IF NOT EXISTS MOVIELENS_DB;

-- Create the schema RAW
CREATE SCHEMA IF NOT EXISTS MOVIELENS_DB.RAW;

-- Create the dbt user (use your choice of password)
CREATE USER IF NOT EXISTS 
    LOGIN_NAME = 'dbt',
    PASSWORD = '',
    MUST_CHANGE_PASSWORD = FALSE,
    DEFAULT_ROLE = 'TRANSFORM',
    DEFAULT_WAREHOUSE = 'COMPUTE_WH',
    DEFAULT_NAMESPACE = 'MOVIELENS_DB.RAW';

-- Give dbt user access to role TRANSFORM
GRANT ROLE TRANSFORM TO USER dbt;

-- Give privileges to WAREHOUSE warehouse to TRANSFORM role.
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
-- Give privileges to MOVIELENS_DB database to TRANSFORM role.
GRANT ALL ON DATABASE MOVIELENS_DB TO ROLE TRANSFORM; 
-- Give privileges to schemas in MOVIELENS_DB database to TRANSFORM role.
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS_DB TO ROLE TRANSFORM; 
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS_DB TO ROLE TRANSFORM; 
-- Give privileges to all tables in RAW schema to TRANSFORM role.
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS_DB.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS_DB.RAW TO ROLE TRANSFORM;